algo: aurora

# General
n_generations: 20
log_interval: 10
batch_size: 256

# Repertoire
repertoire_size: 1024

# GA emitter
iso_sigma: 0.005
line_sigma: 0.05

# Evaluation
fitness: pos_linear_velocity_avg
secondary_fitness: null
secondary_fitness_weight: 1.
n_keep: 16

# AE
features: 128
hidden_size: 6

train_ratio: 8
lr_init_value: 5e-4
lr_end_value: 0.
lr_transition_steps: 0
lr_transition_begin: 0
ae_batch_size: 256

n_keep_ae: 128
use_data_augmentation: True
